### PR TITLE
Allow worker pool to be disabled at compile time

### PR DESCRIPTION
**Pull request by vancemiller**
Enabled by default

### CODE REVIEW

**Comment by yuhc** [comment]
Shouldn't it be an input argument to the managers?

**Comment by vancemiller** [comment]
Yeah, there's no reason it has to be a compile-time decision.

**Comment by vancemiller** [comment]
What's the preferred mechanism for parsing args? the demo manager doesn't do any argument parsing.

**Comment by yuhc** [comment]
> What's the preferred mechanism for parsing args? the demo manager doesn't do any argument parsing.

I was looking at https://github.com/jarro2783/cxxopts and Boost.Program_options, and I prefer the latter one. What's your thoughts?

**Comment by yuhc** [comment]
FYI, I'm working on it in [yuhc/ava/worker_options](https://github.com/yuhc/ava/tree/worker_options).

**Comment by yuhc** [comment]
Reimplemented this in #89.

**Pull request closed without merging**
