### PR TITLE
Add Dockerfile for cuda-10.2

### PR DESCRIPTION
**Pull request by vancemiller**
Add another dockerfile for cuda-10.2.

Rename the original cuda Dockerfile to cuda-11.2

### CODE REVIEW

**Comment by vancemiller** [comment]
The cuda build doesn't work in the 10.2 container yet. What version is expected to work?

```
Traceback (most recent call last):
  File "/home/vance/Documents/workspace/a100-bench/third_party/ava/cava/nwcc", line 9, in <module>
    nightwatch.main.main()
  File "/home/vance/Documents/workspace/a100-bench/third_party/ava/cava/nightwatch/main.py", line 76, in main
    write_file_c(*header.types_header(api, errors), indent=False, filename_prefix=filename_prefix)
  File "/home/vance/Documents/workspace/a100-bench/third_party/ava/cava/nightwatch/indent.py", line 21, in write_file_c
    fi.write(indent_c(data) if indent else data)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 138270: ordinal not in range(128)
CMakeFiles/cava.dir/build.make:134: recipe for target 'ava-llvm/src/cava-stamp/cava-cudadrv-nwcc' failed
make[5]: *** [ava-llvm/src/cava-stamp/cava-cudadrv-nwcc] Error 1
CMakeFiles/Makefile2:96: recipe for target 'CMakeFiles/cava.dir/all' failed
```

**Comment by yuhc** [comment]
I remember that this is a Python dependency issue with CAvA. I'll take a try on this image.

BTW, the current CUDART spec doesn't support CUDA >=10.2. CUDA 10.2 is kind of an alpha version of CUDA 11 whose internal APIs have been changed quite a bit from CUDA 10.1. For example, the behavior of how a CUDART program registers a fat binary is different. That's the main reason why I stopped upgrading the spec to support CUDA 11 because I had to reverse engineer those APIs.

**Comment by yuhc** [comment]
Could you add a README that instructs how to build the docker images and dependencies (e.g. nvidia-container-runtime-hook), and how to build AvA inside the docker?

I tried ava-cuda-10.2 and ava-cuda-11.2 and both got this error:
```
Traceback (most recent call last):
  File "/home/ubuntu/ava/cava/nwcc", line 9, in <module>
    nightwatch.main.main()
  File "/home/ubuntu/ava/cava/nightwatch/main.py", line 49, in main
    from .parser import c
  File "/home/ubuntu/ava/cava/nightwatch/parser/c/__init__.py", line 3, in <module>
    from .rules import *
  File "/home/ubuntu/ava/cava/nightwatch/parser/c/rules.py", line 2, in <module>
    from .clanginterface import *
  File "/home/ubuntu/ava/cava/nightwatch/parser/c/clanginterface.py", line 21, in <module>
    _config_clang()
  File "/home/ubuntu/ava/cava/nightwatch/parser/c/clanginterface.py", line 10, in _config_clang
    from clang import cindex
ModuleNotFoundError: No module named 'clang'
```

Seems something is going wrong with the libclang dependencies.

**Comment by vancemiller** [comment]
Steps to build:

```
# PWD is ava repository root
./tools/docker/run_docker.sh ava-cuda-10.1
mkdir -p build
cd build
rm * -rf 
cmake .. -DAVA_GEN_CUDADRV_SPEC=On -DAVA_MANAGER_LEGACY=On
make
```

**Comment by yuhc** [comment]
The encoding error happens because `cuda.h` for CUDA 10.1 is ASCII text, but that for CUDA 10.2+ is UTF-8 Unicode text.
I've fixed this issue in master and tested all three dockers.

**Pull request merged**
